apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: op53fnh55-java-springboot
  janus-idp.io/tekton: op53fnh55-java-springboot
  backstage.io/kubernetes-id: op53fnh55-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: op53fnh55-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
